import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/app/context/ThemeContext"
import { LanguageProvider } from "@/app/context/LanguageContext"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FeastIQ - Intelligent Restaurant & Food Delivery App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} >
      <body className="min-h-full flex flex-col bg-white dark:bg-[#1A1310] text-gray-800 dark:text-slate-100 font-sans transition-colors duration-300">
  <ThemeProvider>
    <LanguageProvider>
      {children}
      </LanguageProvider>
  </ThemeProvider>
</body>
    </html>
  );
}
